python --device=0 --config_method=configs/config_comp_0.5_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.1_N_01_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.5_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.1_N_01_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.5_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.1_N_01_sigma_0_lr_0.1.yaml ;
python --device=0 --config_method=configs/config_comp_0.5_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.1_N_02_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.5_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.1_N_02_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.5_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.1_N_02_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.5_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.1_N_04_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.5_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.1_N_04_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.5_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.1_N_04_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.5_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.1_N_06_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.5_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.1_N_06_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.5_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.1_N_06_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.5_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.1_N_10_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.5_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.1_N_10_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.5_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.1_N_10_sigma_0_lr_0.1.yaml ;
python --device=0 --config_method=configs/config_comp_0.5_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.5_N_01_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.5_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.5_N_01_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.5_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.5_N_01_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.5_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.5_N_02_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.5_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.5_N_02_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.5_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.5_N_02_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.5_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.5_N_04_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.5_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.5_N_04_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.5_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.5_N_04_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.5_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.5_N_06_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.5_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.5_N_06_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.5_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.5_N_06_sigma_0_lr_0.1.yaml ;
python --device=0 --config_method=configs/config_comp_0.5_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.5_N_10_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.5_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.5_N_10_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.5_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.5_N_10_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.5_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_2_N_01_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.5_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_2_N_01_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.5_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_2_N_01_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.5_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_2_N_02_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.5_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_2_N_02_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.5_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_2_N_02_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.5_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_2_N_04_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.5_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_2_N_04_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.5_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_2_N_04_sigma_0_lr_0.1.yaml ;
python --device=0 --config_method=configs/config_comp_0.5_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_2_N_06_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.5_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_2_N_06_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.5_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_2_N_06_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.5_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_2_N_10_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.5_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_2_N_10_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.5_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_2_N_10_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.1_N_01_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.1_N_01_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.1_N_01_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.1_N_02_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.1_N_02_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.1_N_02_sigma_0_lr_0.1.yaml ;
python --device=0 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.1_N_04_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.1_N_04_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.1_N_04_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.1_N_06_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.1_N_06_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.1_N_06_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.1_N_10_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.1_N_10_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.1_N_10_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.5_N_01_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.5_N_01_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.5_N_01_sigma_0_lr_0.1.yaml ;
python --device=0 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.5_N_02_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.5_N_02_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.5_N_02_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.5_N_04_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.5_N_04_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.5_N_04_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.5_N_06_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.5_N_06_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.5_N_06_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.5_N_10_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.5_N_10_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.5_N_10_sigma_0_lr_0.1.yaml ;
python --device=0 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_2_N_01_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_2_N_01_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_2_N_01_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_2_N_02_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_2_N_02_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_2_N_02_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_2_N_04_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_2_N_04_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_2_N_04_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_2_N_06_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_2_N_06_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_2_N_06_sigma_0_lr_0.1.yaml ;
python --device=0 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_2_N_10_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_2_N_10_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_2_N_10_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.1_N_01_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.1_N_01_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.1_N_01_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.1_N_02_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.1_N_02_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.1_N_02_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.1_N_04_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.1_N_04_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.1_N_04_sigma_0_lr_0.1.yaml ;
python --device=0 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.1_N_06_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.1_N_06_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.1_N_06_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.1_N_10_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.1_N_10_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.1_N_10_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.5_N_01_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.5_N_01_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.5_N_01_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.5_N_02_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.5_N_02_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.5_N_02_sigma_0_lr_0.1.yaml ;
python --device=0 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.5_N_04_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.5_N_04_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.5_N_04_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.5_N_06_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.5_N_06_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.5_N_06_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.5_N_10_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.5_N_10_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.5_N_10_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_2_N_01_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_2_N_01_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_2_N_01_sigma_0_lr_0.1.yaml ;
python --device=0 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_2_N_02_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_2_N_02_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_2_N_02_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_2_N_04_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_2_N_04_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_2_N_04_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_2_N_06_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_2_N_06_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_2_N_06_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_2_N_10_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_2_N_10_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.5_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_2_N_10_sigma_0_lr_0.1.yaml ;
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_squared_euclidean_pow_1.1_N_01_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_squared_euclidean_pow_1.1_N_01_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_squared_euclidean_pow_1.1_N_01_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_squared_euclidean_pow_1.1_N_02_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_squared_euclidean_pow_1.1_N_02_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_squared_euclidean_pow_1.1_N_02_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_squared_euclidean_pow_1.1_N_04_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_squared_euclidean_pow_1.1_N_04_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_squared_euclidean_pow_1.1_N_04_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_squared_euclidean_pow_1.1_N_06_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_squared_euclidean_pow_1.1_N_06_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_squared_euclidean_pow_1.1_N_06_sigma_0_lr_0.1.yaml ;
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_squared_euclidean_pow_1.1_N_10_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_squared_euclidean_pow_1.1_N_10_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_squared_euclidean_pow_1.1_N_10_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_squared_euclidean_pow_1.5_N_01_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_squared_euclidean_pow_1.5_N_01_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_squared_euclidean_pow_1.5_N_01_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_squared_euclidean_pow_1.5_N_02_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_squared_euclidean_pow_1.5_N_02_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_squared_euclidean_pow_1.5_N_02_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_squared_euclidean_pow_1.5_N_04_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_squared_euclidean_pow_1.5_N_04_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_squared_euclidean_pow_1.5_N_04_sigma_0_lr_0.1.yaml ;
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_squared_euclidean_pow_1.5_N_06_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_squared_euclidean_pow_1.5_N_06_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_squared_euclidean_pow_1.5_N_06_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_squared_euclidean_pow_1.5_N_10_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_squared_euclidean_pow_1.5_N_10_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_squared_euclidean_pow_1.5_N_10_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_squared_euclidean_pow_2_N_01_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_squared_euclidean_pow_2_N_01_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_squared_euclidean_pow_2_N_01_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_squared_euclidean_pow_2_N_02_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_squared_euclidean_pow_2_N_02_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_squared_euclidean_pow_2_N_02_sigma_0_lr_0.1.yaml ;
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_squared_euclidean_pow_2_N_04_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_squared_euclidean_pow_2_N_04_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_squared_euclidean_pow_2_N_04_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_squared_euclidean_pow_2_N_06_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_squared_euclidean_pow_2_N_06_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_squared_euclidean_pow_2_N_06_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_squared_euclidean_pow_2_N_10_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_squared_euclidean_pow_2_N_10_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_squared_euclidean_pow_2_N_10_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_power_quaternion_pow_1.1_N_01_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_power_quaternion_pow_1.1_N_01_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_power_quaternion_pow_1.1_N_01_sigma_0_lr_0.1.yaml ;
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_power_quaternion_pow_1.1_N_02_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_power_quaternion_pow_1.1_N_02_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_power_quaternion_pow_1.1_N_02_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_power_quaternion_pow_1.1_N_04_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_power_quaternion_pow_1.1_N_04_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_power_quaternion_pow_1.1_N_04_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_power_quaternion_pow_1.1_N_06_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_power_quaternion_pow_1.1_N_06_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_power_quaternion_pow_1.1_N_06_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_power_quaternion_pow_1.1_N_10_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_power_quaternion_pow_1.1_N_10_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_power_quaternion_pow_1.1_N_10_sigma_0_lr_0.1.yaml ;
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_power_quaternion_pow_1.5_N_01_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_power_quaternion_pow_1.5_N_01_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_power_quaternion_pow_1.5_N_01_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_power_quaternion_pow_1.5_N_02_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_power_quaternion_pow_1.5_N_02_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_power_quaternion_pow_1.5_N_02_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_power_quaternion_pow_1.5_N_04_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_power_quaternion_pow_1.5_N_04_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_power_quaternion_pow_1.5_N_04_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_power_quaternion_pow_1.5_N_06_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_power_quaternion_pow_1.5_N_06_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_power_quaternion_pow_1.5_N_06_sigma_0_lr_0.1.yaml ;
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_power_quaternion_pow_1.5_N_10_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_power_quaternion_pow_1.5_N_10_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_power_quaternion_pow_1.5_N_10_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_power_quaternion_pow_2_N_01_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_power_quaternion_pow_2_N_01_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_power_quaternion_pow_2_N_01_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_power_quaternion_pow_2_N_02_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_power_quaternion_pow_2_N_02_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_power_quaternion_pow_2_N_02_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_power_quaternion_pow_2_N_04_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_power_quaternion_pow_2_N_04_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_power_quaternion_pow_2_N_04_sigma_0_lr_0.1.yaml ;
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_power_quaternion_pow_2_N_06_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_power_quaternion_pow_2_N_06_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_power_quaternion_pow_2_N_06_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_power_quaternion_pow_2_N_10_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_power_quaternion_pow_2_N_10_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_ker_power_quaternion_pow_2_N_10_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_squared_euclidean_pow_1.1_N_01_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_squared_euclidean_pow_1.1_N_01_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_squared_euclidean_pow_1.1_N_01_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_squared_euclidean_pow_1.1_N_02_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_squared_euclidean_pow_1.1_N_02_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_squared_euclidean_pow_1.1_N_02_sigma_0_lr_0.1.yaml ;
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_squared_euclidean_pow_1.1_N_04_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_squared_euclidean_pow_1.1_N_04_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_squared_euclidean_pow_1.1_N_04_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_squared_euclidean_pow_1.1_N_06_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_squared_euclidean_pow_1.1_N_06_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_squared_euclidean_pow_1.1_N_06_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_squared_euclidean_pow_1.1_N_10_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_squared_euclidean_pow_1.1_N_10_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_squared_euclidean_pow_1.1_N_10_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_squared_euclidean_pow_1.5_N_01_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_squared_euclidean_pow_1.5_N_01_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_squared_euclidean_pow_1.5_N_01_sigma_0_lr_0.1.yaml ;
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_squared_euclidean_pow_1.5_N_02_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_squared_euclidean_pow_1.5_N_02_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_squared_euclidean_pow_1.5_N_02_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_squared_euclidean_pow_1.5_N_04_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_squared_euclidean_pow_1.5_N_04_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_squared_euclidean_pow_1.5_N_04_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_squared_euclidean_pow_1.5_N_06_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_squared_euclidean_pow_1.5_N_06_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_squared_euclidean_pow_1.5_N_06_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_squared_euclidean_pow_1.5_N_10_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_squared_euclidean_pow_1.5_N_10_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_squared_euclidean_pow_1.5_N_10_sigma_0_lr_0.1.yaml ;
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_squared_euclidean_pow_2_N_01_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_squared_euclidean_pow_2_N_01_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_squared_euclidean_pow_2_N_01_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_squared_euclidean_pow_2_N_02_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_squared_euclidean_pow_2_N_02_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_squared_euclidean_pow_2_N_02_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_squared_euclidean_pow_2_N_04_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_squared_euclidean_pow_2_N_04_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_squared_euclidean_pow_2_N_04_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_squared_euclidean_pow_2_N_06_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_squared_euclidean_pow_2_N_06_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_squared_euclidean_pow_2_N_06_sigma_0_lr_0.1.yaml ;
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_squared_euclidean_pow_2_N_10_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_squared_euclidean_pow_2_N_10_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_squared_euclidean_pow_2_N_10_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.1_N_01_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.1_N_01_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.1_N_01_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.1_N_02_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.1_N_02_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.1_N_02_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.1_N_04_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.1_N_04_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.1_N_04_sigma_0_lr_0.1.yaml ;
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.1_N_06_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.1_N_06_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.1_N_06_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.1_N_10_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.1_N_10_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.1_N_10_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.5_N_01_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.5_N_01_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.5_N_01_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.5_N_02_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.5_N_02_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.5_N_02_sigma_0_lr_0.1.yaml ;
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.5_N_04_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.5_N_04_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.5_N_04_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.5_N_06_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.5_N_06_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.5_N_06_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.5_N_10_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.5_N_10_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_1.5_N_10_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_2_N_01_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_2_N_01_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_2_N_01_sigma_0_lr_0.1.yaml ;
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_2_N_02_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_2_N_02_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_2_N_02_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_2_N_04_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_2_N_04_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_2_N_04_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_2_N_06_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_2_N_06_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_2_N_06_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_2_N_10_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_2_N_10_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_mmd_opt_SGD_unconstrained_ker_power_quaternion_pow_2_N_10_sigma_0_lr_0.1.yaml ;
python --device=0 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.1_N_01_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.1_N_01_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.1_N_01_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.1_N_02_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.1_N_02_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.1_N_02_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.1_N_04_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.1_N_04_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.1_N_04_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.1_N_06_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.1_N_06_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.1_N_06_sigma_0_lr_0.1.yaml ;
python --device=0 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.1_N_10_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.1_N_10_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.1_N_10_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.5_N_01_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.5_N_01_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.5_N_01_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.5_N_02_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.5_N_02_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.5_N_02_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.5_N_04_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.5_N_04_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.5_N_04_sigma_0_lr_0.1.yaml ;
python --device=0 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.5_N_06_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.5_N_06_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.5_N_06_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.5_N_10_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.5_N_10_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_1.5_N_10_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_2_N_01_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_2_N_01_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_2_N_01_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_2_N_02_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_2_N_02_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_2_N_02_sigma_0_lr_0.1.yaml ;
python --device=0 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_2_N_04_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_2_N_04_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_2_N_04_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_2_N_06_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_2_N_06_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_2_N_06_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_2_N_10_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_2_N_10_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_squared_euclidean_pow_2_N_10_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.1_N_01_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.1_N_01_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.1_N_01_sigma_0_lr_0.1.yaml ;
python --device=0 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.1_N_02_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.1_N_02_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.1_N_02_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.1_N_04_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.1_N_04_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.1_N_04_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.1_N_06_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.1_N_06_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.1_N_06_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.1_N_10_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.1_N_10_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.1_N_10_sigma_0_lr_0.1.yaml ;
python --device=0 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.5_N_01_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.5_N_01_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.5_N_01_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.5_N_02_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.5_N_02_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.5_N_02_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.5_N_04_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.5_N_04_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.5_N_04_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.5_N_06_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.5_N_06_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.5_N_06_sigma_0_lr_0.1.yaml ;
python --device=0 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.5_N_10_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.5_N_10_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_1.5_N_10_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_2_N_01_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_2_N_01_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_2_N_01_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_2_N_02_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_2_N_02_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_2_N_02_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_2_N_04_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_2_N_04_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_2_N_04_sigma_0_lr_0.1.yaml ;
python --device=0 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_2_N_06_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_2_N_06_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_2_N_06_sigma_0_lr_0.1.yaml &
python --device=0 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_2_N_10_sigma_0_lr_0.01.yaml &
python --device=1 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_2_N_10_sigma_0_lr_0.05.yaml &
python --device=2 --config_method=configs/config_comp_0.7_loss_sinkhorn_opt_SGD_ker_power_quaternion_pow_2_N_10_sigma_0_lr_0.1.yaml &
