#### problem
completeness : 0.1
model : 'real_data'
true_prior : 'gaussian'
num_true_particles : 1
true_product_particles : True
true_rm_noise_level : -1.
true_bernoulli_noise : -1.

batch_size : 70000

with_edges_splits : True
data_name : 'marker'
data_path : '../data/'
log_name : marker_sink_prod_gt
lr : 0.001
log_dir : /nfs/gatsbystor/michaela/projects/OptSync

dtype : '64'
particles_type : 'quaternion'
optimizer : 'SGD'
prior : 'gaussian'
loss : 'sinkhorn'

# kernel_cost : 'power_quaternion'
# with_weights : 1
# product_particles : 1
# num_particles : 20

kernel_cost : 'power_quaternion'
with_weights : 1
product_particles : 1
num_particles : 10
power : 1.2
with_couplings : False
weights_factor : .1
conjugate : True
GT_mode : False
err_tol : 0.0001 
#weights_factor: 1.



#python -m ipdb train.py --device=2 --config_data=configs/notredame.yaml 


#python train_sacred.py with device=-1 config_data=configs/notredame.yaml 



