#### problem
completeness : 0.1
model : 'synthetic'
true_prior : 'gaussian'
num_true_particles : 1
true_product_particles : True
true_rm_noise_level : -1.
true_bernoulli_noise : -1.
unfaithfulness : False

