
log_dir: '/nfs/data/michaela/projects/OptSync'
dtype : '64'
particles_type : 'quaternion'
optimizer : 'SGD'
prior : 'gaussian'
loss : 'sinkhorn'


# kernel_cost : 'power_quaternion'
# with_weights : 1
# product_particles : 1
# num_particles : 20



kernel_cost : 'power_quaternion'
with_weights : 1
product_particles : 1
num_particles : 10
power : 1.2
with_couplings : True
weights_factor : .01
#weights_factor: 1.