log_dir: '/nfs/data/michaela/projects/OptSync'
dtype : '32'
seed : 0
total_iters : 10000
lr : 0.1
particles_type : 'quaternion'

#### method
optimizer : 'SGD'
prior : 'gaussian'

loss : 'sinkhorn'
kernel_cost : 'power_quaternion'
with_weights : 1
product_particles : 1
num_particles : 10

#### problem
completeness : 0.1
model : 'synthetic'
true_prior : 'gaussian'
num_true_particles : 1
true_product_particles : False
true_rm_noise_level : -1.
true_bernoulli_noise : -1.
unfaithfulness : False